name: Sync to GitLab

on:
  push:
    branches:
      - main   # branch que você quer sincronizar

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Push para GitLab
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.auditto.com.br/giovanna.fernandes/Atestto.git
          git push --mirror gitlab
